name: CI

on:
    push:
    pull_request:

jobs:
    ci:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node:
              - 18
              - 19
              - 20

        steps:
            - name: 'Init repository'
              uses: actions/checkout@v3
            - name: 'Setup node'
              uses: actions/setup-node@v3
              with:
                node-version: ${{matrix.node}}
            - name: 'Install dependencies'
              run: npm install
            - name: 'Run linter'
              run: npx eslint
            - name: 'Run mocha'
              run: npm test